# Generated by Django 5.1.3 on 2024-11-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2),
        ),
        migrations.AlterField(
            model_name='todo',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
